name: Treehacker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}  # login shell so conda works

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-name: treeenv
          auto-activate-base: false
          activate-environment: treeenv
          channels: conda-forge,bioconda
          packages: newick_utils raxml-ng

      - name: Install APT packages (samtools, etc)
        run: |
          sudo apt update
          sudo apt install -y samtools bedtools bioawk bc seqtk

      - name: Run TREEhacker and raxml-ng check
        run: |
          which raxml-ng
          raxml-ng --help
          ./TREEhacker_1.0.sh --help
          ./TREEhacker_1.0.sh test/fastafiles.txt test 20 20 0.5 DNA

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Test with testthat
        working-directory: ./test
        run: |
          Rscript ./treehacker_test.R
